### ISSUE TITLE
THIS IS CRAP,  UGLY. ...if you intend it to be open source you should mean it

### ISSUE THREAD

**Issue by Julisons** [tjscience/audion#9]
This is so ugly and doesn't look like the images on the documentation, it's better to host the WinForm control of the original CScore in the WPF app...   you're mean

**Comment by Julisons** [comment]
1. You make us download a large file only to fine a stupid video file.
2 Your test example doesn't work..... (DID YOU EVEN TEST IT? )
3.Your github documentation are outdated. 
4.You should decide if you want to open source a project not give out shot and hold the real dll.

**Comment by filoe** [comment]
Probably you should rethink your type of communication. This is not constructive at all.

**Comment by tjscience** [comment]
@Julisons I am not really sure what you are talking about. If you are saying that the sample application is ugly, keep in mind that this is a work in progress and is not even in alpha phase yet. That being said, the sample app is not exactly up to par at the moment. I realize there are many issues and they are currently being worked on. However, if you really wanted to see some of these visualization, you could create your own sample app. 

I don't understand why you think I should host the Winform control of original cscore in the WPF app... This library is meant to be a WPF framework to create visualizations and other controls in WPF, for cscore. 

The comment about not being open source does not make sense. The license on audion is MIT, which is pretty permissive in my opinion. Can you elaborate on why you do not think audion is open source?

Hopefully, you are happier with the next commit of audion which will be more of a complete project. Also, while I do welcome constructive criticism, calling things ugly and crap doesn't help anyone. I take pride in that fact that I write code and share that code with a community of open source developers and I do so not because I have to, but because I really do wish to contribute what I can back to the community.
